version: '2.3'

services:
  db:
    image: postgres:16.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Wallet-Service-db